version: '3.8'

services:
  telegram_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        echo 'Checking environment variables...' &&
        echo 'TELEGRAM_TOKEN exists:' &&
        [ ! -z \"$$TELEGRAM_TOKEN\" ] &&
        echo 'Starting bot...' &&
        python main.py
      "
